"""add task assignment

Revision ID: 896b23782238
Revises: cd4ebe7aa505
Create Date: 2026-09-20 22:20:59.164756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "896b23782238"
down_revision: Union[str, Sequence[str], None] = "cd4ebe7aa505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("assigned_to", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_tasks_assigned_to_users", "tasks", "users", ["assigned_to"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_tasks_assigned_to_users", "tasks", type_="foreignkey")
    op.drop_column("tasks", "assigned_to")
    # ### end Alembic commands ###
