"""add tenant timestamps

Revision ID: 8d3836098baa
Revises: 1cf7cb87dd0d
Create Date: 2026-09-18 16:16:27.230032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3836098baa'
down_revision: Union[str, Sequence[str], None] = '1cf7cb87dd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    # ### end Alembic commands ###
